routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RequestWithdrawController;
use App\Http\Controllers\UsersController;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->action([HomeController::class, 'index']);
});

Auth::routes([
    'register' => false,
    'reset' => false,
    'verify' => false,
]);

Route::get('/home', [HomeController::class, 'index'])->name('home');
Route::get('/user', [UsersController::class, 'index'])->name('user.index');

Route::resource('users', UsersController::class);
Route::get('/membership',[UsersController::class, 'membership'])->name('membership');
Route::get('/status-wd',[RequestWithdrawController::class, 'index'])->name('statuswd');
Route::post('/status-wd',[RequestWithdrawController::class, 'store'])->name('statuswd.store');

resources/views/content/view_membership.blade.php
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>{{$title}}</h2>
            </div>
            <div class="card-body">
                <div class="col-md-12">
                  <form id="formUser" method="POST" action="{{ route('users.store') }}">
                    @csrf
                    <input type="hidden" name="bonus_id" id="bonus_id" value="1">
                    <div class="form-group">
                      <label for="name">Nama
                        <span class="text-danger">*</span>
                      </label>
                      <input type="text" name="name" class="form-control" id="name" placeholder="Masukkan Nama" autofocus><br>
                    </div>
                    <div class="form-group">
                      <label for="name">Email 
                        <span class="text-danger">*</span>
                      </label>
                      <input type="email" name="email" class="form-control" id="email" placeholder="Masukkan Email"><br>
                    </div>
                    @if(auth()->user()->role_id == 1)
                      <div class="form-group">
                      <label for="name">Role
                        <span class="text-danger">*</span>
                      </label>
                      <select name="role_id" class="form-control" id="role_id">
                            <option value="-">Pilih Role</option>
                            <option value="1">Admin</option>
                            <option value="2" selected>Member</option>
                        </select><br>
                    </div>
                    @else
                      <input type="hidden" name="role_id" value="2">
                    @endif
                    @if(auth()->user()->role_id == 1)
                      <div class="form-group">
                        <label for="name">Referensi User
                          <span class="text-danger">*</span>
                        </label>
                        <select name="reference_id" class="form-control" id="reference_id">
                              <option value="-">Pilih Referensi User</option>
                              @foreach ($users as $user)
                              <option value="{{ $user->id }}">{{ $user->name }}</option>
                              @endforeach
                          </select><br>
                      </div>
                    @else
                      <input type="hidden" name="reference_id" value="{{ auth()->user()->id }}">
                    @endif
                    
                    <div class="form-group">
                      <label for="name">Password
                        <span class="text-danger">*</span>
                      </label>
                      <input type="text" name="password" class="form-control" placeholder="Masukkan Password"><br>
                    </div>
                    <button type="submit" class="btn btn-primary btn-block">Submit</button>
                  </form>
                </div>
            </div>
        </div>
    </div>
</div>

resources/views/content/view_user.blade.php
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>{{$title}}</h2>
                <div class="d-flex flex-row-reverse"><button
                        class="btn btn-sm btn-pill btn-outline-primary font-weight-bolder" id="createNewUser"><i
                            class="fas fa-plus"></i>Add data </button>
                </div>
            </div>
            <div class="card-body">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table" id="tableUser">
                            <thead class="font-weight-bold text-center">
                                <tr>
                                    {{-- <th>No.</th> --}}
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th style="width:90px;">Action</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                                {{-- @foreach ($users as $r_users)
                                    <tr>
                                <td>{{$r_users->id}}</td>
                                <td>{{$r_users->name}}</td>
                                <td>{{$r_users->email}}</td>
                                <td>{{$r_users->role_id}}</td>
                                <td>
                                    <div class="btn btn-success editUser" data-id="{{$r_users->id}}">Edit</div>
                                    <div class="btn btn-danger deleteUser" data-id="{{$r_users->id}}">Delete</div>
                                </td>
                                </tr>
                                @endforeach --}}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal-->
<div class="modal fade" id="modal-user" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="exampleModalLabel">Modal User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <form id="formUser" name="formUser">
                    <div class="form-group">

                        <input type="text" name="name" class="form-control" id="name" placeholder="Nama"><br>
                        <input type="email" name="email" class="form-control" id="email" placeholder="email"><br>
                        <select name="role_id" class="form-control" id="role_id">
                            <option value="-">Pilih Role</option>
                            <option value="1">Operator</option>
                            <option value="2">Member</option>
                        </select><br>
                        <input type="text" name="password" class="form-control" placeholder="password"><br>
                        <input type="hidden" name="user_id" id="user_id" value="">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary font-weight-bold" id="saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>



@push('scripts')
<script>
    $('document').ready(function () {
        // success alert
        function swal_success() {
            Swal.fire({
                position: 'top-end',
                icon: 'success',
                title: 'Your work has been saved',
                showConfirmButton: false,
                timer: 1000
            })
        }
        // error alert
        function swal_error() {
            Swal.fire({
                position: 'centered',
                icon: 'error',
                title: 'Something goes wrong !',
                showConfirmButton: true,
            })
        }
        // table serverside
        var table = $('#tableUser').DataTable({
            processing: false,
            serverSide: true,
            ordering: false,
            dom: 'Bfrtip',
            buttons: [
                'copy', 'excel', 'pdf'
            ],
            ajax: "{{ route('users.index') }}",
            columns: [{
                    data: 'name',
                    name: 'name'
                },
                {
                    data: 'email',
                    name: 'email'
                },
                {
                    data: 'role_id',
                    name: 'role_id'
                },
                {
                    data: 'action',
                    name: 'action',
                    orderable: false,
                    searchable: false
                },
            ]
        });
        
        // csrf token
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
        // initialize btn add
        $('#createNewUser').click(function () {
            $('#saveBtn').val("create user");
            $('#user_id').val('');
            $('#formUser').trigger("reset");
            $('#modal-user').modal('show');
        });
        // initialize btn edit
        $('body').on('click', '.editUser', function () {
            var user_id = $(this).data('id');
            $.get("{{route('users.index')}}" + '/' + user_id + '/edit', function (data) {
                $('#saveBtn').val("edit-user");
                $('#modal-user').modal('show');
                $('#user_id').val(data.id);
                $('#name').val(data.name);
                $('#email').val(data.email);
                $('#role_id').val(data.role_id);
            })
        });
        // initialize btn save
        $('#saveBtn').click(function (e) {
            e.preventDefault();
            $(this).html('Save');

            $.ajax({
                data: $('#formUser').serialize(),
                url: "{{ route('users.store') }}",
                type: "POST",
                dataType: 'json',
                success: function (data) {

                    $('#formUser').trigger("reset");
                    $('#modal-user').modal('hide');
                    swal_success();
                    table.draw();

                },
                error: function (data) {
                    swal_error();
                    $('#saveBtn').html('Save Changes');
                }
            });

        });
        // initialize btn delete
        $('body').on('click', '.deleteUser', function () {
            var user_id = $(this).data("id");

            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "DELETE",
                        url: "{{route('users.store')}}" + '/' + user_id,
                        success: function (data) {
                            swal_success();
                            table.draw();
                        },
                        error: function (data) {
                            swal_error();
                        }
                    });
                }
            })
        });

        // statusing


    });

</script>
@endpush

resources/views/content/view_withdraw.blade.php
@if ($message = Session::get('success'))
  <div class="alert alert-info alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>    
    <strong>{{ $message }}</strong>
  </div>
@endif
<div class="content d-flex flex-column flex-column-fluid" id="kt_content">
    <div class="container">
        <div class="card">
            <div class="card-header">
                <h2>{{$title}}</h2>
                <div class="d-flex flex-row-reverse">
                  <button class="btn btn-sm btn-pill btn-outline-primary font-weight-bolder" id="requestWithdraw"><i class="fas fa-plus"></i>
                    Request Withdraw
                  </button>
                </div>
            </div>
            <div class="card-body">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table class="table" id="tableUser">
                            <thead class="font-weight-bold text-center">
                                <tr>
                                    <th>No.</th>
                                    <th>Total WD</th>
                                    <th>Status</th>
                                </tr>
                            </thead>
                            <tbody class="text-center">
                                @forelse ($withdraws as $wd)
                                  <tr>
                                    <td>{{$loop->iteration}}</td>
                                    <td>{{$wd->total_wd}}</td>
                                    <td>
                                      <span class="badge badge-pill {{$wd->status == 'request' ? 'badge-warning' : ($wd->status == 'success' ? 'badge-success' : 'badge-danger')}}">{{$wd->status}}</span>
                                    </td>
                                  </tr>
                                @empty

                                @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal-->
<div class="modal fade" id="modal-request-wd" data-backdrop="static" tabindex="-1" role="dialog"
    aria-labelledby="staticBackdrop" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h5 class="modal-title text-white" id="exampleModalLabel">Modal User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <i aria-hidden="true" class="ki ki-close"></i>
                </button>
            </div>
            <div class="modal-body">
                <form id="request-wd" method="POST" action="{{ route('statuswd.store') }}" autocomplete="off">
                  @csrf
                  <input type="hidden" name="status" id="status" value="request">
                    <div class="form-group">
                      <label>Total bonus yang dimiliki : {{ $total_bonus }}</label><br>
                      <label for="total_wd">Total Withdraw</label>
                      <input type="text" name="total_wd" class="form-control" id="total_wd" placeholder="Total Withdraw"><br>
                      <label id="message-wd"></label>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Tutup</button>
                <button type="button" class="btn btn-primary font-weight-bold" id="saveBtn">Submit</button>
            </div>
        </div>
    </div>
</div>

@push('scripts')
<script>
    $('document').ready(function () {
        $('#requestWithdraw').click(function () {
            $('#saveBtn').val("Request Withdraw");
            $('#user_id').val('');
            $('#request-wd').trigger("reset");
            $('#modal-request-wd').modal('show');                           
        });

        $('#saveBtn').on('click', function(e){
          let totalWd = $('#total_wd').val();
          if (parseInt(totalWd, 10) > {{ $total_bonus }}) {
            alert(`Withdraw melebihi bonus yang dimiliki!`);
            $('#total_wd').focus();
          } else if(totalWd === ''){
            alert(`Withdraw tidak boleh kosong!`);
            $('#total_wd').focus();
          } else if(!parseInt(totalWd, 10)){
            alert('Isi dengan angka!');
            $('#total_wd').focus();
          } else if(parseInt(totalWd, 10) < 0){
            alert('Withdraw tidak boleh kurang dari 0!');
            $('#total_wd').focus();
          }
          else {
            $('#request-wd').submit();
          }
        });

        $('#total_wd').on('keyup', function(e){
          let total_wd = parseInt($(this).val(), 10);
          if (total_wd) {
            let sisa = {{ $total_bonus }} - total_wd;
            if (sisa < 0) {
              $('#message-wd').attr('class', 'text-danger');
            }
            else {
              $('#message-wd').attr('class', 'text-warning');
            }
            $('#message-wd').text('Total bonus yang dimiliki : ' + sisa);
          } else {
            $('#message-wd').text('');
          }
        });
    });
</script>
@endpush